FROM python:3.4

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements_dev.txt ./
RUN pip install -r requirements.txt
COPY . .
ENV DJANGO_SETTINGS_MODULE=bitext_matching.settings_dev

EXPOSE 8000
ENTRYPOINT ["/code/docker-entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
