version: '2'

services:
  db:
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    environment:
      DJANGO_MANAGEPY_MIGRATE: on
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
