version: '3.1'
services:
    db:
        image: mysql
        ports:
            - 8001:3306
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        restart: always
    adminer:
        image: adminer
        restart: always
        ports:
            - 8002:8080
