# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180205_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alignment', models.IntegerField()),
                ('bitext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='core.Bitext')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('bitext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Bitext')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='bitext',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='translation',
            name='word_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_1', to='core.Word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_2', to='core.Word'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='core.Alignment'),
        ),
    ]
