# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180205_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignment',
            options={'ordering': ['id_alignment']},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['id_par']},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['id_sen']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='sentence',
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='english', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(to='core.Sentence'),
        ),
    ]
