# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180205_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitext',
            options={'ordering': ['creation_date']},
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='text',
            new_name='content',
        ),
    ]
