# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180207_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['score']},
        ),
        migrations.AddField(
            model_name='bitext',
            name='alignments_number',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
